project_id = "xafoyjtagyqljqbpcepv"

[functions.upload-emotion]
verify_jwt = true

[functions.ai-emotion-response]
verify_jwt = false

[functions.get-encrypted-blob]
verify_jwt = false

[functions.get-emotions-by-wallet]
verify_jwt = false

[functions.get-emotions]
verify_jwt = true
